spring:
  datasource:
    username: ${DB_PASSWORD:postgres}
    password: ${DB_PASSWORD:postgres}
    name: ${DB_NAME:foodApp}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5555}/${DB_NAME:FoodApp}

  jpa:
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs

server:
  port: 8080
