CREATE TABLE users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    email varchar NOT NULL UNIQUE,
    age smallint NOT NULL CHECK (age > 0 AND age < 100),
    weight numeric(5, 2) NOT NULL CHECK (weight > 2 AND weight < 350),
    height numeric(5, 2) NOT NULL CHECK (height > 50 AND height < 250),
    status varchar(15) CHECK (status IN ('WEIGHT_LOSS', 'WEIGHT_GAIN', 'RECOMPOSITION', 'MAINTAINING'))
);

CREATE TABLE user_norms (
    user_id bigint NOT NULL,
    calorie_norm numeric(8, 2),
    protein_norm numeric(8, 2),
    fat_norm numeric(8, 2),
    carbs_norm numeric(8, 2),

    CONSTRAINT pkey_user_id PRIMARY KEY (user_id),
    CONSTRAINT fkey_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE dishes (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    calories numeric(8,2) CHECK (calories >= 0 AND calories <= 862),
    protein numeric(8,2) CHECK (protein >= 0 AND protein <= 100),
    fat numeric(8,2) CHECK (fat >= 0 AND fat <= 100),
    carbs numeric(8,2) CHECK (carbs >= 0 AND carbs <= 100),

    CONSTRAINT check_sum CHECK (protein+fat+carbs <= 100)
);

CREATE TABLE food_stats (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    dish_id bigint,
    status varchar(10) NOT NULL CHECK (status IN ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK')),
    grams numeric(8,2) NOT NULL CHECK (grams > 0),
    total_calories numeric(8,2),
    total_protein numeric(8,2),
    total_fat numeric(8,2),
    total_carbs numeric(8,2),
    created_at timestamp,

    CONSTRAINT fkey_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fkey_dish_id FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE SET NULL
);

